export const DEFAULT_API_BASE_URL = 'https://api.scalemule.com';
export const DEFAULT_WS_RECONNECT_BASE_DELAY = 1000;
export const DEFAULT_WS_RECONNECT_MAX_DELAY = 30000;
export const DEFAULT_WS_RECONNECT_MAX_RETRIES = Infinity;
export const DEFAULT_WS_HEARTBEAT_INTERVAL = 30000;
export const DEFAULT_MESSAGE_CACHE_SIZE = 200;
export const DEFAULT_MAX_CONVERSATIONS_CACHED = 50;
export const DEFAULT_REQUEST_TIMEOUT = 10000;
